from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .models import (
    CatalogEntry,
    DiagnosticsReport,
    DiagnosticsSummary,
    FileDiagnostic,
    OverlapCandidate,
)


def build_index(input_dir: Path, entries: list[CatalogEntry]) -> dict[str, Any]:
    return {
        "schema_version": "0.1.0",
        "source_root": input_dir.name,
        "synthetic_example": input_dir.name == "sample-collection",
        "entry_count": len(entries),
        "entries": [entry.to_dict() for entry in entries],
    }


def build_overlap_report(
    input_dir: Path, candidates: list[OverlapCandidate]
) -> dict[str, Any]:
    return {
        "schema_version": "0.1.0",
        "source_root": input_dir.name,
        "synthetic_example": input_dir.name == "sample-collection",
        "candidate_count": len(candidates),
        "candidates": [candidate.to_dict() for candidate in candidates],
    }


def build_diagnostics(
    input_dir: Path,
    files: list[FileDiagnostic],
    generated_at: str | None = None,
) -> DiagnosticsReport:
    return DiagnosticsReport(
        schema_version="0.1.0",
        source_root=input_dir.name,
        generated_at=generated_at or _generated_at(),
        summary=DiagnosticsSummary.from_files(files),
        files=files,
    )


def render_markdown(index: dict[str, Any]) -> str:
    lines = [
        "# Artifact Catalog",
        "",
        "> Generated by agent-librarian. Review metadata and overlap findings "
        "before making catalog or consolidation decisions.",
        "",
    ]
    if index.get("synthetic_example"):
        lines.extend(
            [
                "> This catalog was generated from a synthetic, public-safe example collection.",
                "",
            ]
        )
    lines.extend(
        [
            "## Summary",
            "",
            f"- Source: `{index['source_root']}`",
            f"- Entries: {index['entry_count']}",
            f"- Schema version: `{index['schema_version']}`",
            "",
            "## Entries",
            "",
        ]
    )

    for entry in index["entries"]:
        lines.extend(
            [
                f"### {entry['name']}",
                "",
                f"- ID: `{entry['id']}`",
                f"- Type: `{entry['artifact_type']}`",
                f"- Taxonomy bucket: {entry['taxonomy_bucket']}",
                f"- Framework hint: {entry['framework_hint'] or 'None'}",
                f"- Source: `{entry['source_path']}`",
                f"- Description: {entry['description'] or 'Not provided'}",
                f"- Purpose: {entry['purpose'] or 'Not provided'}",
                f"- Activation triggers: {_items(entry['activation_triggers'])}",
                f"- Inputs: {_items(entry['inputs'])}",
                f"- Outputs: {_items(entry['outputs'])}",
                f"- Tools: {_items(entry['tool_scope'])}",
                f"- Side effects: {_items(entry['side_effects'])}",
                f"- Dependencies: {_items(entry['dependencies'])}",
                f"- Tags: {_items(entry['tags'])}",
                f"- Warnings: {_items(entry['discoverability_warnings'])}",
                f"- Extraction confidence: {entry['extraction'].get('confidence', 'unknown')}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def write_outputs(
    output_dir: Path,
    index: dict[str, Any],
    overlap_report: dict[str, Any],
    diagnostics: DiagnosticsReport,
) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = [
        output_dir / "index.json",
        output_dir / "catalog.md",
        output_dir / "overlap-report.json",
        output_dir / "diagnostics.json",
    ]
    paths[0].write_text(_json(index), encoding="utf-8")
    paths[1].write_text(render_markdown(index), encoding="utf-8")
    paths[2].write_text(_json(overlap_report), encoding="utf-8")
    paths[3].write_text(_json(diagnostics.to_dict()), encoding="utf-8")
    return paths


def _items(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) if values else "Not provided"


def _json(value: dict[str, Any]) -> str:
    return json.dumps(value, indent=2, sort_keys=False) + "\n"


def _generated_at() -> str:
    source_date_epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if source_date_epoch is not None:
        timestamp = datetime.fromtimestamp(int(source_date_epoch), tz=timezone.utc)
    else:
        timestamp = datetime.now(timezone.utc)
    return timestamp.replace(microsecond=0).isoformat().replace("+00:00", "Z")
